
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
---
title: "Project 2 - KNN-adina"
author: ""
date: "today"
# date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    # number_sections: true
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r basic, include=F}
# use this function to conveniently load libraries and work smoothly with knitting
# can add quietly=T option to the require() function
# the loadPkg function essentially replaced/substituted two functions install.packages() and library() in one step.
loadPkg = function(x) { if (!require(x,character.only=T, quietly =T)) { install.packages(x,dep=T,repos="http://cran.us.r-project.org"); if(!require(x,character.only=T)) stop("Package not found") } }

# unload/detact package when done using it
unloadPkg = function(pkg, character.only = FALSE) { 
  if(!character.only) { pkg <- as.character(substitute(pkg)) } 
  search_item <- paste("package", pkg,sep = ":") 
  while(search_item %in% search()) { detach(search_item, unload = TRUE, character.only = TRUE) } 
}
```

```{r setup, include=FALSE}
# some of common options (and the defaults) are: 
# include=T, eval=T, echo=T, results='hide'/'asis'/'markup',..., collapse=F, warning=T, message=T, error=T, cache=T, fig.width=6, fig.height=4, fig.dim=c(6,4) #inches, fig.align='left'/'center','right', 
# knitr::opts_chunk$set(warning = F, results = "markup", message = F)
knitr::opts_chunk$set(warning = F, results = "hide", message = F)
# knitr::opts_chunk$set(include = F)
# knitr::opts_chunk$set(echo = TRUE)
options(scientific=T, digits = 3) 
# options(scipen=9, digits = 3) 
# ‘scipen’: integer. A penalty to be applied when deciding to print numeric values in fixed or exponential notation.  Positive values bias towards fixed and negative towards scientific notation: fixed notation will be preferred unless it is more than ‘scipen’ digits wider.
# use scipen=999 to prevent scientific notation at all times
```

```{r xkablesummary}
loadPkg("xtable")
loadPkg("kableExtra")
loadPkg("stringi")

xkabledply = function(modelsmmrytable, title="Table", digits = 4, pos="left", bso="striped", wide=FALSE) { 
  #' Combining base::summary, xtable, and kableExtra, to easily display model summary. 
  #' wrapper for the base::summary function on model objects
  #' Can also use as head for better display
  #' ELo 202004 GWU DATS
  #' version 1.2
  #' @param modelsmmrytable This can be a generic table, a model object such as lm(), or the summary of a model object summary(lm()) 
  #' @param title Title of table. 
  #' @param digits Number of digits to display
  #' @param pos Position of table, c("left","center","right") 
  #' @param bso bootstrap_options = c("basic", "striped", "bordered", "hover", "condensed", "responsive")
  #' @param wide print table in long (FALSE) format or wide (TRUE) format
  #' @return HTML table for display
  #' @examples
  #' library("xtable")
  #' library("kableExtra")
  #' xkabledply( df, title="Table testing", pos="left", bso="hover" )
  #' xkabledply( ISLR::Hitters[1:5,] )
  if (wide) { modelsmmrytable <- t(modelsmmrytable) }
  modelsmmrytable %>%
    xtable() %>% 
    kable(caption = title, digits = digits) %>%
    kable_styling(bootstrap_options = bso, full_width = FALSE, position = pos)
}

xkabledplyhead = function(df, rows=5, title="Head", digits = 4, pos="left", bso="striped") { 
  xkabledply(df[1:rows, ], title, digits, pos, bso, wide=FALSE)
}

xkabledplytail = function(df, rows=5, title="Tail", digits = 4, pos="left", bso="striped") { 
  trows = nrow(df)
  xkabledply(df[ (trows-rows+1) : trows, ], title, digits, pos, bso, wide=FALSE)
}

xkablesummary = function(df, title="Table: Statistics summary.", digits = 4, pos="left", bso="striped") { 
  #' Combining base::summary, xtable, and kableExtra, to easily display numeric variable summary of dataframes. 
  #' ELo 202004 GWU DATS
  #' version 1.2
  #' @param df The dataframe.
  #' @param title Title of table. 
  #' @param digits Number of digits to display
  #' @param pos Position of table, c("left","center","right") 
  #' @param bso bootstrap_options = c("basic", "striped", "bordered", "hover", "condensed", "responsive")
  #' @return The HTML summary table for display, or for knitr to process into other formats 
  #' @examples
  #' xkablesummary( faraway::ozone )
  #' xkablesummary( ISLR::Hitters, title="Five number summary", pos="left", bso="hover"  )
  
  s = summary(df) %>%
    apply( 2, function(x) stringr::str_remove_all(x,c("Min.\\s*:\\s*","1st Qu.\\s*:\\s*","Median\\s*:\\s*","Mean\\s*:\\s*","3rd Qu.\\s*:\\s*","Max.\\s*:\\s*")) ) %>% # replace all leading words
    apply( 2, function(x) stringr::str_trim(x, "right")) # trim trailing spaces left
  
  colnames(s) <- stringr::str_trim(colnames(s))
  
  if ( dim(s)[1] ==6 ) { rownames(s) <- c('Min','Q1','Median','Mean','Q3','Max') 
  } else if ( dim(s)[1] ==7 ) { rownames(s) <- c('Min','Q1','Median','Mean','Q3','Max','NA') }
  
  xkabledply(s, title=title, digits = digits, pos=pos, bso=bso )
}

xkablevif = function(model, title="VIFs of the model", digits = 3, pos="left", bso="striped", wide=TRUE) { 
  #' Combining faraway::vif, xtable, and kableExtra, to easily display numeric summary of VIFs for a model. 
  #' ELo 202004 GWU DATS
  #' version 1.2
  #' @param model The lm or compatible model object.
  #' @param title Title of table. 
  #' @param digits Number of digits to display
  #' @param pos Position of table, c("left","center","right") 
  #' @param bso bootstrap_options = c("basic", "striped", "bordered", "hover", "condensed", "responsive")
  #' @param wide print table in long (FALSE) format or wide (TRUE) format
  #' @return The HTML summary table of the VIFs for a model for display, or for knitr to process into other formats 
  #' @examples
  #' xkablevif( lm(Salary~Hits+RBI, data=ISLR::Hitters), wide=T )
  
  vifs = table( names(model$coefficients)[2:length(model$coefficients)] ) # remove intercept to set column names
  vifs[] = faraway::vif(model) # set the values
  if (wide) { vifs <- t(vifs) }
  xkabledply( vifs, title=title, digits = digits, pos=pos, bso=bso )
}
```


```{r, results="markup"}
telco_data <- data.frame(read.csv("telecom_users_updated.csv"))

sapply(telco_data, function(x) sum(is.na(x)))

telco_data <- na.omit(telco_data)

xkablesummary(telco_data)

sapply(telco_data, function(x) sum(is.na(x)))
```
```{r , results='markup'}
str(telco_data)
```


```{r, results="markup"}

telco_data$gender <- as.factor(telco_data$gender)
telco_data$SeniorCitizen<-as.factor(telco_data$SeniorCitizen)
telco_data$Partner <- as.factor(telco_data$Partner)
telco_data$Dependents <- as.factor(telco_data$Dependents)
telco_data$PhoneService <- as.factor(telco_data$PhoneService)
telco_data$MultipleLines <- as.factor(telco_data$MultipleLines)
telco_data$InternetService <- as.factor(telco_data$InternetService)
telco_data$OnlineSecurity <- as.factor(telco_data$OnlineSecurity)
telco_data$OnlineBackup <- as.factor(telco_data$OnlineBackup)
telco_data$DeviceProtection <- as.factor(telco_data$DeviceProtection)
telco_data$TechSupport <- as.factor(telco_data$TechSupport)
telco_data$StreamingTV <- as.factor(telco_data$StreamingTV)
telco_data$StreamingMovies <- as.factor(telco_data$StreamingMovies)
telco_data$Contract <- as.factor(telco_data$Contract)
telco_data$PaperlessBilling <- as.factor(telco_data$PaperlessBilling)
telco_data$PaymentMethod <- as.factor(telco_data$PaymentMethod)
telco_data$Churn <- as.factor(telco_data$Churn)

```

```{r , results='markup'}
telco_data_new = subset(telco_data, select = -c(gender,SeniorCitizen,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies ,Contract,PaperlessBilling,PaymentMethod) ) 
```

```{r , results='markup'}
telco_data_updated= subset(telco_data_new , select = -c(X , customerID))
```

```{r}
telco_data_updated$MonthlyCharges<-as.integer(telco_data_updated$MonthlyCharges)
telco_data_updated$TotalCharges<-as.integer(telco_data_updated$TotalCharges)
```

```{r , results='markup'}
telco_data_updated

```
```{r}
str(telco_data_updated)
```


```{r , results='markup'}
#first we want to scale the data so KNN will operate correctly
telcom_data <- as.data.frame(scale(telco_data_updated[1:3], center = TRUE, scale = TRUE))
 
set.seed(1000)
data <- sample(2, nrow(telcom_data), replace=TRUE, prob=c(0.67, 0.33))

data_training <- telcom_data[data==1, 1:3]
data_test <- telcom_data[data==2, 1:3]
```

```{r}
#Now we need to create our 'Y' variables or labels need to input into the KNN function
data.trainLabels<- telco_data_updated[data==1,4]
data.testLabels<-telco_data_updated[data==2,4]
```

```{r}
telcom_data
```

```{r , results='markup'}
loadPkg("FNN")
#So now we will deploy our model  for k value= 2 
data_pred <- knn(train = data_training, test = data_test, cl=data.trainLabels, k=2)
```


```{r , results='markup'}
loadPkg("gmodels")
datapredcross <- CrossTable(data.testLabels, data_pred, prop.chisq = FALSE)
#Looks like we got all but three correct, not bad
```

```{r , results='markup'}
loadPkg("caret") 
data_pred5 <- knn(train = data_training, test = data_test, cl=data.trainLabels, k=2)
cm = confusionMatrix(data_pred, reference = data.testLabels )
```

```{r , results='markup'}
loadPkg("gmodels")
loadPkg("FNN")
loadPkg("caret")
cmaccu = cm$overall['Accuracy']

print( paste("Total Accuracy = ", cmaccu ) )
```




